############################################################
swagger: '2.0'
############################################################

############################################################
info:
  version: "0.0.1"
  title: ms-gen sample
  description: |
    GET method, without parameter, and returning one value.
############################################################

############################################################
paths:
############################################################

  ############################################################
  /get_method_1:
  ############################################################
    get:
      description: |
        GET method, without parameter, and returning one value.
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/GetMethod1Response"

############################################################
definitions:
############################################################

  ############################################################
  GetMethod1Response:
  ############################################################
    type: object
    properties:
      fieldName1:
        type: string
        description: Field 1.
