############################################################
swagger: '2.0'
############################################################

############################################################
info:
  version: "0.0.1"
  title: ms-gen sample
  description: |
    Tests to msg_gen.
  x-serviceName: myservice
############################################################

############################################################
paths:
############################################################

  ############################################################
  /get_method_1:
  ############################################################
    get:
      description: |
        GET method, without parameter, and returning one value.
      operationId: getMethod1
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/GetMethod1Response"

  ############################################################
  /get_method_2:
  ############################################################
    get:
      description: |
        GET method, without parameter, and returning two values.
      operationId: getMethod2
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/GetMethod2Response"

  ############################################################
  /get_method_3:
  ############################################################
    get:
      description: |
        GET method, without parameter, and returning three values.
      operationId: getMethod3
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/GetMethod3Response"

  ##########################################################
  /get_method_4/{par1}:
  ##########################################################
    get:
      description: |
        GET method, one parameter, and returning one value.
      operationId: getMethod4
      parameters:
        - in: path
          name: par1
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/GetMethod4Response"

  ##########################################################
  /get_method_5:
  ##########################################################
    get:
      description: |
        GET method, one parameter in query, and returning some values.
      operationId: getMethod5
      parameters:
        - in: query
          name: queryPar1
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/GetMethod5Response"

  ##########################################################
  /get_method_6:
  ##########################################################
    get:
      description: |
        GET method, two parameters in query, and returning some values.
      operationId: getMethod6
      parameters:
        - in: query
          name: queryPar1
          type: string
        - in: query
          name: queryPar2
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/GetMethod6Response"

  ##########################################################
  /get_method_7:
  ##########################################################
    get:
      description: |
        GET method, one parameter in query, and can return 200 or 400.
      operationId: getMethod7
      parameters:
        - in: query
          name: queryPar
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/GenericResponseWithSomeFields"
        400:
          description: Invalid parameter

  ##########################################################
  /get_method_8:
  ##########################################################
    get:
      description: |
        GET method, one parameter in query, and can return 200 or 400 with error information.
      operationId: getMethod8
      parameters:
        - in: query
          name: queryPar
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/GenericResponseWithSomeFields"
        400:
          description: Invalid parameter
          schema:
            $ref: "#/definitions/ErrorResponse"

  ##########################################################
  /path_2:
  ##########################################################
    get:
      description: |
        GET method, one parameter in query, and can return 200 or 400 with error information.
      operationId: path2Get1
      parameters:
        - in: query
          name: queryPar
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/GenericResponseWithSomeFields"
        400:
          description: Invalid parameter
          schema:
            $ref: "#/definitions/ErrorResponse"

    post:
      description: |
        POST method, and can return 200 or 400.
      operationId: path2Post1
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/GenericResponseWithSomeFields"
        400:
          description: Invalid parameter
          schema:
            $ref: "#/definitions/ErrorResponse"

  ##########################################################
  /path_3:
  ##########################################################
    post:
      description: |
        Post with arguments in the body, returning some result values in 200 and 400.
      operationId: path3Post
      parameters:
        - in: body
          name: path3PostRequest
          schema:
            $ref: "#/definitions/Path3PostRequest"
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/GenericResponseWithSomeFields"
        400:
          description: Invalid parameter
          schema:
            $ref: "#/definitions/ErrorResponse"

  ##########################################################
  /path_4/{par}:
  ##########################################################
    put:
      description: |
        Put with one parameter, without data in body, result code 204.
      operationId: path4Put
      parameters:
        - in: path
          name: par
          required: true
          type: string
      responses:
        204:
          description: Successful response
        400:
          description: Invalid parameter
          schema:
            $ref: "#/definitions/ErrorResponse"

  ##########################################################
  /path_5/{par}:
  ##########################################################
    put:
      description: |
        Put with one parameter, without data in body, result code 200.
      operationId: path5Put
      parameters:
        - in: path
          name: par
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/GenericResponseWithSomeFields"
        400:
          description: Invalid parameter
          schema:
            $ref: "#/definitions/ErrorResponse"

  ##########################################################
  /path_6/{par}:
  ##########################################################
    put:
      description: |
        Put with one parameter, with data in body, result code 204.
      operationId: path6Put
      parameters:
        - in: path
          name: par
          required: true
          type: string
        - in: body
          name: path6PutRequest
          schema:
            $ref: "#/definitions/GenericBodyRequestWithSomeFields"
      responses:
        204:
          description: Successful response
        400:
          description: Invalid parameter
          schema:
            $ref: "#/definitions/ErrorResponse"

  ##########################################################
  /path_7/{par}:
  ##########################################################
    put:
      description: |
        Put with one parameter, with data in body, result code 200.
      operationId: path7Put
      parameters:
        - in: path
          name: par
          required: true
          type: string
        - in: body
          name: path7PutRequest
          schema:
            $ref: "#/definitions/GenericBodyRequestWithSomeFields"
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/GenericResponseWithSomeFields"
        400:
          description: Invalid parameter
          schema:
            $ref: "#/definitions/ErrorResponse"


############################################################
definitions:
############################################################

  ############################################################
  GetMethod1Response:
  ############################################################
    type: object
    properties:
      fieldName1:
        type: string
        description: Field 1.

  ############################################################
  GetMethod2Response:
  ############################################################
    type: object
    properties:
      fieldName1:
        type: string
        description: Field 1.
      fieldName2:
        type: string
        description: Field 2.

  ############################################################
  GetMethod3Response:
  ############################################################
    type: object
    properties:
      fieldName1:
        type: string
        description: Field 1.
      fieldName2:
        type: number
        description: Field 2.
      fieldName3:
        type: integer
        description: Field 3.
      fieldName4:
        type: boolean
        description: Field 4.

  ############################################################
  GetMethod4Response:
  ############################################################
    type: object
    properties:
      fieldName1:
        type: string
        description: Field 1.

  ############################################################
  GetMethod5Response:
  ############################################################
    type: object
    properties:
      fieldName1:
        type: string
        description: Field 1.
      fieldName2:
        type: number
        description: Field 2.
      fieldName3:
        type: integer
        description: Field 3.
      fieldName4:
        type: boolean
        description: Field 4.

  ############################################################
  GetMethod6Response:
  ############################################################
    type: object
    properties:
      fieldName1:
        type: string
        description: Field 1.
      fieldName2:
        type: number
        description: Field 2.
      fieldName3:
        type: integer
        description: Field 3.
      fieldName4:
        type: boolean
        description: Field 4.

  ############################################################
  GenericBodyRequestWithSomeFields:
  ############################################################
    type: object
    properties:
      fieldName1:
        type: string
        description: Field 1.
      fieldName2:
        type: number
        description: Field 2.
      fieldName3:
        type: integer
        description: Field 3.
      fieldName4:
        type: boolean
        description: Field 4.
  
  ############################################################
  GenericResponseWithSomeFields:
  ############################################################
    type: object
    properties:
      fieldName1:
        type: string
        description: Field 1.
      fieldName2:
        type: number
        description: Field 2.
      fieldName3:
        type: integer
        description: Field 3.
      fieldName4:
        type: boolean
        description: Field 4.
  
  ############################################################
  Path3PostRequest:
  ############################################################
    type: object
    properties:
      fieldName1:
        type: string
        description: Field 1.
      fieldName2:
        type: number
        description: Field 2.
      fieldName3:
        type: integer
        description: Field 3.
      fieldName4:
        type: boolean
        description: Field 4.
  
  ##########################################################
  ErrorResponse:
  ##########################################################
    type: object
    required:
      - errorCode
      - errorMessage
    properties:
      errorCode:
        type: string
      errorMessage:
        type: string
